In [ ]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.miscmodels.ordinal_model import OrderedModel

ANES_YEAR_MIN = 1972 # Lower limit of years to consider for ANES-based model

anes_full = pd.read_csv('raw_data/anes_timeseries_cdf_csv_20260205/anes_timeseries_cdf_csv_20260205.csv')
anes_full = anes_full.rename(columns={
    "VCF0803": "voter_ideo", #Ideological self-placement scale
    "VCF9096": "gop_ideo", #Respondent rating of gop candidate on ideology scale
    "VCF9088": "dem_ideo", #Respondentt rating of dem candidate on ideology scale
    "VCF0830": "voter_blacks", #Government aid to blacks question, selected due to time continuity from 1972-2024
    "VCF9092": "gop_blacks", #Respondent rating of gop candidate on gov't aid to blacks
    "VCF9084": "dem_blacks", #Respondent rating of dem candidate on gov't aid to blacks
    "VCF0901a": "state_fips",
    "VCF0004": "year"})
anes_full['state_fips'] = pd.to_numeric(anes_full['state_fips'], errors='coerce').astype('Int64')

# Merge with state postal codes (for interpretability) and region codes
state_codes = pd.read_csv('raw_data/state_fips.csv')
anes_full = pd.merge(anes_full, state_codes, on='state_fips', how='left')
regions = pd.read_csv('raw_data/us_regions_divisions.csv')
regions = regions.rename(columns = {'State': 'state_name', 'State Code': 'state', 'Region': 'census_region', 'Division': 'division'})
anes_full = pd.merge(anes_full, regions[['state','census_region','division']], on = 'state', how = 'left')
bea_regions = pd.read_csv('raw_data/statelevel_predictors.csv')
anes_full = pd.merge(anes_full, bea_regions[['state','bea_region','pol_south']], on = 'state', how = 'left')

# Add state partisanship data to better predict distribution of ideology within states
state_partisanship = pd.read_stata('raw_data/1868_2020_presvote.dta')
state_partisanship['natl_rvote'] = (state_partisanship.groupby('year')['rvote']
        .transform(lambda x: x[state_partisanship.loc[x.index, 'state'] == 'US'].iloc[0]))
state_partisanship['rlean'] = state_partisanship['rvote'] - state_partisanship['natl_rvote']
state_partisanship['rlean_rolling2'] = (state_partisanship.groupby('state')['rlean']
        .rolling(window = 2, min_periods = 1).mean().reset_index(level=0, drop=True) 
)
state_partisanship = state_partisanship[state_partisanship['year'] >= ANES_YEAR_MIN]
anes_full = pd.merge(anes_full, state_partisanship[['year','state','rlean','rlean_rolling2']], on = ['state', 'year'], how = 'left')
anes_full['rlean'] = anes_full.groupby('state')['rlean'].ffill() #fill missing values in mid-election year with rlean from previous year
anes_full['rlean_rolling2'] = anes_full.groupby('state')['rlean_rolling2'].ffill()
# TODO: Extract 'totev' from the state partisanship data to model electoral votes

# Join mass economic and policy liberalism measures from Caughey Warshaw 2018 with ANES respondent ideology data
caughey_warshaw = pd.read_stata('/Users/marcetter/Dropbox/writing_sample/caughey_warshaw_2018_replication/caughey_warshaw_summary.dta')
caughey_warshaw = caughey_warshaw.rename(columns = {'stpo': 'state'})
caughey_warshaw['year'] = caughey_warshaw['year'].astype('int64')
anes_full = pd.merge(anes_full, caughey_warshaw[['year','state','masseconlib_est','masssociallib_est']], on = ['state','year'], how = 'left')
#extrapolate most recent estimates in 2014 to 2024
anes_full['masseconlib_est'] = anes_full.groupby('state')['masseconlib_est'].ffill()
anes_full['masssociallib_est'] = anes_full.groupby('state')['masssociallib_est'].ffill()

anes_full['voter_ideo'] = pd.to_numeric(anes_full['voter_ideo'], errors='coerce')
anes_full['voter_ideo'] = anes_full['voter_ideo'].apply(lambda x: np.nan if x == 9.0 or x == 0.0 else x)
anes_full['voter_blacks'] = pd.to_numeric(anes_full['voter_blacks'], errors='coerce')
anes_full['voter_blacks'] = anes_full['voter_blacks'].apply(lambda x: np.nan if x == 9.0 or x == 0.0 else x)

## Create predictor variables for ordinal model
anes_full['state_fips'] = anes_full['state_fips'].astype('string')
anes_full['decade'] = ((anes_full['year'] // 10) * 10).astype('string')
#anes['year_categorical'] = anes['year'].astype('category')
anes_full['year_center'] = anes_full['year'] - 2000
anes_full['year_center_sq'] = anes_full['year_center']**2

anes = anes_full[[
    'state','state_fips',
    'voter_ideo','voter_blacks',
    'year', 'year_center', 'year_center_sq', 'decade',
    'census_region','division','bea_region',
    'masseconlib_est', 'masssociallib_est',
    'rlean','rlean_rolling2']]
anes = anes[anes['year'] >= ANES_YEAR_MIN]

<positron-console-cell-83>:9: DtypeWarning: Columns (0: VCF0009x, 1: VCF0010x, 2: VCF0011x, 3: VCF0009y, 4: VCF0010y, 5: VCF0011y, 6: VCF9999, 7: VCF0012, 8: VCF0015a, 9: VCF0015b, 10: VCF0016, 11: VCF0018a, 12: VCF0018b, 13: VCF0019, 14: VCF0050a, 15: VCF0050b, 16: VCF0070a, 17: VCF0070b, 18: VCF0071a, 19: VCF0071b, 20: VCF0071c, 21: VCF0071d, 22: VCF0072a, 23: VCF0072b, 24: VCF0101, 25: VCF0105a, 26: VCF0105b, 27: VCF0106, 28: VCF0107, 29: VCF0108, 30: VCF0109, 31: VCF0111, 32: VCF0112, 33: VCF0113, 34: VCF0114, 35: VCF0115, 36: VCF0116, 37: VCF0117, 38: VCF0118, 39: VCF0119, 40: VCF0120, 41: VCF0121, 42: VCF0122, 43: VCF0123, 44: VCF0124, 45: VCF0125, 46: VCF0126, 47: VCF0126a, 48: VCF0126b, 49: VCF0126c, 50: VCF0127, 51: VCF0127a, 52: VCF0127b, 53: VCF0128, 54: VCF0128a, 55: VCF0128b, 56: VCF0129, 57: VCF0130, 58: VCF0130a, 59: VCF0131, 60: VCF0132, 61: VCF0133, 62: VCF0134, 63: VCF0135, 64: VCF0136, 65: VCF0137, 66: VCF0138, 67: VCF0138a, 68: VCF0138b, 69: VCF0138c, 70: VCF0138d, 71: VCF0138e, 72: VCF0139, 73: VCF0140, 74: VCF0140a, 75: VCF0141, 76: VCF0142, 77: VCF0143, 78: VCF0144, 79: VCF0145, 80: VCF0146, 81: VCF0147, 82: VCF0148, 83: VCF0148a, 84: VCF0149, 85: VCF0150, 86: VCF0151, 87: VCF0152, 88: VCF0153a, 89: VCF0153b, 90: VCF0153c, 91: VCF0154a, 92: VCF0154b, 93: VCF0155, 94: VCF0156, 95: VCF0157, 96: VCF0170a, 97: VCF0170b, 98: VCF0170c, 99: VCF0170d, 100: VCF0201, 101: VCF0202, 102: VCF0203, 103: VCF0204, 104: VCF0205, 105: VCF0206, 106: VCF0207, 107: VCF0208, 108: VCF0209, 109: VCF0210, 110: VCF0211, 111: VCF0212, 112: VCF0213, 113: VCF0214, 114: VCF0215, 115: VCF0216, 116: VCF0217, 117: VCF0218, 118: VCF0219, 119: VCF0220, 120: VCF0221, 121: VCF0222, 122: VCF0223, 123: VCF0224, 124: VCF0225, 125: VCF0226, 126: VCF0227, 127: VCF0228, 128: VCF0229, 129: VCF0230, 130: VCF0231, 131: VCF0232, 132: VCF0233, 133: VCF0234, 134: VCF0235, 135: VCF0236, 136: VCF0253, 137: VCF0290, 138: VCF0291, 139: VCF0301, 140: VCF0302, 141: VCF0303, 142: VCF0305, 143: VCF0306, 144: VCF0307, 145: VCF0308, 146: VCF0309, 147: VCF0310, 148: VCF0311, 149: VCF0312, 150: VCF0313, 151: VCF0314, 152: VCF0315, 153: VCF0316, 154: VCF0317, 155: VCF0318, 156: VCF0319, 157: VCF0320, 158: VCF0321, 159: VCF0322, 160: VCF0323, 161: VCF0324, 162: VCF0338, 163: VCF0339, 164: VCF0340, 165: VCF0341, 166: VCF0342, 167: VCF0343, 168: VCF0344, 169: VCF0345, 170: VCF0346, 171: VCF0347, 172: VCF0348, 173: VCF0349, 174: VCF0350, 175: VCF0351, 176: VCF0352, 177: VCF0353, 178: VCF0354, 179: VCF0355, 180: VCF0356, 181: VCF0357, 182: VCF0358, 183: VCF0359, 184: VCF0360, 185: VCF0361, 186: VCF0362, 187: VCF0363, 188: VCF0364, 189: VCF0365, 190: VCF0366, 191: VCF0367, 192: VCF0368, 193: VCF0369, 194: VCF0370, 195: VCF0371, 196: VCF0372, 197: VCF0373, 198: VCF0374, 199: VCF0380, 200: VCF0386, 201: VCF0392, 202: VCF0401, 203: VCF0402, 204: VCF0403, 205: VCF0404, 206: VCF0405, 207: VCF0406, 208: VCF0407, 209: VCF0408, 210: VCF0409, 211: VCF0410, 212: VCF0411, 213: VCF0412, 214: VCF0413, 215: VCF0414, 216: VCF0415, 217: VCF0424, 218: VCF0425, 219: VCF0426, 220: VCF0427, 221: VCF0428, 222: VCF0429, 223: VCF0432, 224: VCF0433, 225: VCF0434, 226: VCF0435, 227: VCF0436, 228: VCF0437, 229: VCF0438, 230: VCF0439, 231: VCF0440, 232: VCF0441, 233: VCF0442, 234: VCF0443, 235: VCF0444, 236: VCF0445, 237: VCF0446, 238: VCF0447, 239: VCF0448, 240: VCF0449, 241: VCF0450, 242: VCF0451, 243: VCF0471, 244: VCF0472, 245: VCF0473, 246: VCF0475, 247: VCF0481, 248: VCF0487, 249: VCF0493, 250: VCF0501, 251: VCF0502, 252: VCF0502a, 253: VCF0503, 254: VCF0504, 255: VCF0507, 256: VCF0508, 257: VCF0509, 258: VCF0512, 259: VCF0513, 260: VCF0514, 261: VCF0517, 262: VCF0518, 263: VCF0521, 264: VCF0521a, 265: VCF0522, 266: VCF0523, 267: VCF0524, 268: VCF0525, 269: VCF0528, 270: VCF0529, 271: VCF0533, 272: VCF0534, 273: VCF0537, 274: VCF0538, 275: VCF0541, 276: VCF0542, 277: VCF0545, 278: VCF0546, 279: VCF0549, 280: VCF0550, 281: VCF0601, 282: VCF0602, 283: VCF0603, 284: VCF0604, 285: VCF0605, 286: VCF0606, 287: VCF0607, 288: VCF0608, 289: VCF0609, 290: VCF0610, 291: VCF0611, 292: VCF0612, 293: VCF0613, 294: VCF0614, 295: VCF0615, 296: VCF0616, 297: VCF0617, 298: VCF0618, 299: VCF0619, 300: VCF0620, 301: VCF0621, 302: VCF0622, 303: VCF0623, 304: VCF0624, 305: VCF0625, 306: VCF0626, 307: VCF0627, 308: VCF0628, 309: VCF0629, 310: VCF0630, 311: VCF0631, 312: VCF0632, 313: VCF0633, 314: VCF0634, 315: VCF0640, 316: VCF0648, 317: VCF0649, 318: VCF0650, 319: VCF0651, 320: VCF0652, 321: VCF0653, 322: VCF0654, 323: VCF0655, 324: VCF0656, 325: VCF0675, 326: VCF0700, 327: VCF0701, 328: VCF0702, 329: VCF0703, 330: VCF0704, 331: VCF0704a, 332: VCF0705, 333: VCF0706, 334: VCF0707, 335: VCF0708, 336: VCF0709, 337: VCF0710, 338: VCF0711, 339: VCF0712, 340: VCF0713, 341: VCF0714, 342: VCF0715, 343: VCF0716, 344: VCF0717, 345: VCF0718, 346: VCF0719, 347: VCF0720, 348: VCF0721, 349: VCF0722, 350: VCF0723, 351: VCF0723a, 352: VCF0724, 353: VCF0725, 354: VCF0726, 355: VCF0727, 356: VCF0728, 357: VCF0729, 358: VCF0730, 359: VCF0731, 360: VCF0732, 361: VCF0733, 362: VCF0734, 363: VCF0735, 364: VCF0736, 365: VCF0737, 366: VCF0738, 367: VCF0738a, 368: VCF0739, 369: VCF0740, 370: VCF0741, 371: VCF0742, 372: VCF0743, 373: VCF0744, 374: VCF0745, 375: VCF0746, 376: VCF0747, 377: VCF0748, 378: VCF0749, 379: VCF0750, 380: VCF0801, 381: VCF0803, 382: VCF0804, 383: VCF0805, 384: VCF0806, 385: VCF0808, 386: VCF0809, 387: VCF0811, 388: VCF0813, 389: VCF0814, 390: VCF0815, 391: VCF0816, 392: VCF0817, 393: VCF0818, 394: VCF0819, 395: VCF0820, 396: VCF0821, 397: VCF0822, 398: VCF0823, 399: VCF0824, 400: VCF0825, 401: VCF0826, 402: VCF0827, 403: VCF0827a, 404: VCF0828, 405: VCF0829, 406: VCF0830, 407: VCF0832, 408: VCF0833, 409: VCF0834, 410: VCF0836, 411: VCF0837, 412: VCF0838, 413: VCF0839, 414: VCF0840, 415: VCF0841, 416: VCF0842, 417: VCF0843, 418: VCF0844, 419: VCF0845, 420: VCF0846, 421: VCF0847, 422: VCF0848, 423: VCF0848a, 424: VCF0849, 425: VCF0850, 426: VCF0851, 427: VCF0852, 428: VCF0853, 429: VCF0854, 430: VCF0860, 431: VCF0861, 432: VCF0862, 433: VCF0863, 434: VCF0864, 435: VCF0865, 436: VCF0866, 437: VCF0867, 438: VCF0867a, 439: VCF0870, 440: VCF0871, 441: VCF0872, 442: VCF0873, 443: VCF0875, 444: VCF0875a, 445: VCF0875b, 446: VCF0876, 447: VCF0876a, 448: VCF0877, 449: VCF0877a, 450: VCF0878, 451: VCF0879, 452: VCF0879a, 453: VCF0880, 454: VCF0880a, 455: VCF0880b, 456: VCF0881, 457: VCF0886, 458: VCF0887, 459: VCF0888, 460: VCF0889, 461: VCF0890, 462: VCF0891, 463: VCF0892, 464: VCF0893, 465: VCF0894, 466: VCF0900, 467: VCF0900b, 468: VCF0900c, 469: VCF0901a, 470: VCF0901b, 471: VCF0902, 472: VCF0903, 473: VCF0904, 474: VCF0905, 475: VCF0906, 476: VCF0907, 477: VCF0908, 478: VCF0909, 479: VCF0910, 480: VCF0911, 481: VCF0912, 482: VCF0913, 483: VCF0914, 484: VCF0915, 485: VCF0916, 486: VCF0917, 487: VCF0918, 488: VCF0919, 489: VCF0920, 490: VCF0921, 491: VCF0922, 492: VCF0923, 493: VCF0924, 494: VCF0925, 495: VCF0926, 496: VCF0927, 497: VCF0928, 498: VCF0929, 499: VCF0930, 500: VCF0931, 501: VCF0932, 502: VCF0933, 503: VCF0934, 504: VCF0935, 505: VCF0936, 506: VCF0937, 507: VCF0938, 508: VCF0939, 509: VCF0940, 510: VCF0941, 511: VCF0942, 512: VCF0943, 513: VCF0944, 514: VCF0945, 515: VCF0946, 516: VCF0946a, 517: VCF0947, 518: VCF0947a, 519: VCF0948, 520: VCF0948a, 521: VCF0949, 522: VCF0949a, 523: VCF0950, 524: VCF0951, 525: VCF0952, 526: VCF0953, 527: VCF0954, 528: VCF0955, 529: VCF0956, 530: VCF0957, 531: VCF0958, 532: VCF0959, 533: VCF0960, 534: VCF0961, 535: VCF0962, 536: VCF0963, 537: VCF0964, 538: VCF0965, 539: VCF0966, 540: VCF0967, 541: VCF0968, 542: VCF0969, 543: VCF0970, 544: VCF0971, 545: VCF0972, 546: VCF0973, 547: VCF0974, 548: VCF0975, 549: VCF0976, 550: VCF0977, 551: VCF0978, 552: VCF0980, 553: VCF0981, 554: VCF0982, 555: VCF0983, 556: VCF0984, 557: VCF0985, 558: VCF0986, 559: VCF0987, 560: VCF0988, 561: VCF0989, 562: VCF0990, 563: VCF0991, 564: VCF0992, 565: VCF0993, 566: VCF0994, 567: VCF0995, 568: VCF0996, 569: VCF0997, 570: VCF0998, 571: VCF0999, 572: VCF1000, 573: VCF1001, 574: VCF1002, 575: VCF1003, 576: VCF1004, 577: VCF1005, 578: VCF1006, 579: VCF1007, 580: VCF1008, 581: VCF1009, 582: VCF1010, 583: VCF1011, 584: VCF1012, 585: VCF1013, 586: VCF1014, 587: VCF1015, 588: VCF1016, 589: VCF1017, 590: VCF1018, 591: VCF1020, 592: VCF1026, 593: VCF1032, 594: VCF1038, 595: VCF9001, 596: VCF9002, 597: VCF9003, 598: VCF9004, 599: VCF9005, 600: VCF9006, 601: VCF9007, 602: VCF9008, 603: VCF9009, 604: VCF9010, 605: VCF9011, 606: VCF9012, 607: VCF9013, 608: VCF9014, 609: VCF9015, 610: VCF9016, 611: VCF9017, 612: VCF9018, 613: VCF9019, 614: VCF9020, 615: VCF9021, 616: VCF9022, 617: VCF9023, 618: VCF9024, 619: VCF9025, 620: VCF9026, 621: VCF9027, 622: VCF9028, 623: VCF9029, 624: VCF9030, 625: VCF9030a, 626: VCF9030b, 627: VCF9030c, 628: VCF9031, 629: VCF9032, 630: VCF9033, 631: VCF9034, 632: VCF9035, 633: VCF9036, 634: VCF9037, 635: VCF9038, 636: VCF9039, 637: VCF9040, 638: VCF9041, 639: VCF9042, 640: VCF9043, 641: VCF9043a, 642: VCF9044, 643: VCF9044a, 644: VCF9045, 645: VCF9046, 646: VCF9047, 647: VCF9048, 648: VCF9049, 649: VCF9050, 650: VCF9051, 651: VCF9052, 652: VCF9053, 653: VCF9054, 654: VCF9055, 655: VCF9056, 656: VCF9057, 657: VCF9058, 658: VCF9059, 659: VCF9060, 660: VCF9061, 661: VCF9062, 662: VCF9063, 663: VCF9064, 664: VCF9065, 665: VCF9066, 666: VCF9067, 667: VCF9069, 668: VCF9070, 669: VCF9071, 670: VCF9072, 671: VCF9073, 672: VCF9074, 673: VCF9075, 674: VCF9076, 675: VCF9077, 676: VCF9078, 677: VCF9079, 678: VCF9080, 679: VCF9081, 680: VCF9082, 681: VCF9083, 682: VCF9084, 683: VCF9085, 684: VCF9086, 685: VCF9087, 686: VCF9088, 687: VCF9089, 688: VCF9090, 689: VCF9091, 690: VCF9092, 691: VCF9093, 692: VCF9094, 693: VCF9095, 694: VCF9096, 695: VCF9097, 696: VCF9098, 697: VCF9099, 698: VCF9100, 699: VCF9101, 700: VCF9102, 701: VCF9103, 702: VCF9104, 703: VCF9105, 704: VCF9106, 705: VCF9107, 706: VCF9108, 707: VCF9109, 708: VCF9110, 709: VCF9111, 710: VCF9112, 711: VCF9113, 712: VCF9114, 713: VCF9115, 714: VCF9116, 715: VCF9117, 716: VCF9118, 717: VCF9119, 718: VCF9120, 719: VCF9121, 720: VCF9122, 721: VCF9123, 722: VCF9124, 723: VCF9125, 724: VCF9131, 725: VCF9132, 726: VCF9133, 727: VCF9134, 728: VCF9149, 729: VCF9150, 730: VCF9151, 731: VCF9152, 732: VCF9153, 733: VCF9154, 734: VCF9155, 735: VCF9201, 736: VCF9202, 737: VCF9203, 738: VCF9204, 739: VCF9205, 740: VCF9206, 741: VCF9207, 742: VCF9208, 743: VCF9209, 744: VCF9210, 745: VCF9211, 746: VCF9212, 747: VCF9213, 748: VCF9214, 749: VCF9215, 750: VCF9216, 751: VCF9217, 752: VCF9218, 753: VCF9219, 754: VCF9220, 755: VCF9221, 756: VCF9222, 757: VCF9223, 758: VCF9224, 759: VCF9225, 760: VCF9226, 761: VCF9227, 762: VCF9228, 763: VCF9229, 764: VCF9230, 765: VCF9231, 766: VCF9232, 767: VCF9233, 768: VCF9234, 769: VCF9235, 770: VCF9236, 771: VCF9237, 772: VCF9238, 773: VCF9239, 774: VCF9240, 775: VCF9241, 776: VCF9242, 777: VCF9243, 778: VCF9244, 779: VCF9245, 780: VCF9246, 781: VCF9247, 782: VCF9248, 783: VCF9249, 784: VCF9250, 785: VCF9251, 786: VCF9252, 787: VCF9253, 788: VCF9254, 789: VCF9255, 790: VCF9256, 791: VCF9257, 792: VCF9258, 793: VCF9259, 794: VCF9260, 795: VCF9261, 796: VCF9262, 797: VCF9263, 798: VCF9264, 799: VCF9265, 800: VCF9266, 801: VCF9267, 802: VCF9268, 803: VCF9269, 804: VCF9270, 805: VCF9271, 806: VCF9272, 807: VCF9273, 808: VCF9274, 809: VCF9275, 810: VCF9277, 811: VCF9278, 812: VCF9279, 813: VCF9280, 814: VCF9281, 815: VCF9282) have mixed types. Specify dtype option on import or set low_memory=False.
<positron-console-cell-83>:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
<positron-console-cell-83>:62: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
<positron-console-cell-83>:63: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Fit Ideology Ordinal Response Model to Represent Ideology Distribution as a Function of State and Year

In [ ]:

ideo_data = anes[['voter_ideo', 'state', 
    'rlean_rolling2', 'masssociallib_est', 'masseconlib_est']].dropna().copy()
ideo_model = OrderedModel.from_formula('voter_ideo ~ state + masseconlib_est + masssociallib_est + rlean_rolling2', 
    distr = 'logit', data = ideo_data, hasconst=False).fit(method = 'cg', disp = True)
ideo_model.summary() #switching to method 'cg' (conjugate gradient) from default Nelder Mead resolves convergence warnings

Optimization terminated successfully.
         Current function value: 1.732836
         Iterations: 329
         Function evaluations: 636
         Gradient evaluations: 636

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OrderedModel Results
==============================================================================
Dep. Variable:             voter_ideo   Log-Likelihood:                -72531.
Model:                   OrderedModel   AIC:                         1.452e+05
Method:            Maximum Likelihood   BIC:                         1.457e+05
Date:                Fri, 07 Aug 2026
Time:                        23:38:26
No. Observations:               41857
Df Residuals:                   41799
Df Model:                          52
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
state[T.AL]           0.2140      0.512      0.418      0.676      -0.789       1.217
state[T.AR]           0.1958      0.513      0.382      0.703      -0.809       1.201
state[T.AZ]           0.0464      0.511      0.091      0.928      -0.956       1.048
state[T.CA]          -0.0196      0.509     -0.038      0.969      -1.018       0.979
state[T.CO]          -0.2126      0.511     -0.416      0.677      -1.214       0.789
state[T.CT]          -0.0162      0.514     -0.032      0.975      -1.024       0.992
state[T.DE]          -0.1770      0.549     -0.322      0.747      -1.254       0.900
state[T.FL]           0.1451      0.509      0.285      0.776      -0.853       1.143
state[T.GA]           0.1332      0.510      0.261      0.794      -0.866       1.132
state[T.HI]           0.0243      0.573      0.042      0.966      -1.099       1.147
state[T.IA]           0.1173      0.513      0.229      0.819      -0.887       1.122
state[T.ID]          -0.2315      0.529     -0.438      0.662      -1.269       0.806
state[T.IL]          -0.0338      0.510     -0.066      0.947      -1.034       0.966
state[T.IN]           0.0889      0.510      0.174      0.862      -0.911       1.089
state[T.KS]           0.1466      0.513      0.286      0.775      -0.859       1.152
state[T.KY]          -0.3002      0.515     -0.582      0.560      -1.310       0.710
state[T.LA]           0.1306      0.514      0.254      0.800      -0.877       1.139
state[T.MA]          -0.1201      0.513     -0.234      0.815      -1.126       0.886
state[T.MD]           0.1151      0.513      0.224      0.822      -0.890       1.120
state[T.ME]          -0.1494      0.527     -0.284      0.777      -1.182       0.883
state[T.MI]           0.0484      0.510      0.095      0.924      -0.951       1.048
state[T.MN]           0.0602      0.511      0.118      0.906      -0.941       1.061
state[T.MO]           0.0241      0.510      0.047      0.962      -0.976       1.024
state[T.MS]           0.3501      0.519      0.675      0.500      -0.667       1.367
state[T.MT]          -0.2620      0.557     -0.470      0.638      -1.354       0.830
state[T.NC]           0.0233      0.510      0.046      0.964      -0.976       1.023
state[T.ND]           0.2451      0.538      0.456      0.649      -0.809       1.299
state[T.NE]          -0.0874      0.519     -0.168      0.866      -1.105       0.930
state[T.NH]          -0.1256      0.518     -0.242      0.809      -1.141       0.890
state[T.NJ]           0.0896      0.512      0.175      0.861      -0.914       1.093
state[T.NM]           0.1440      0.521      0.277      0.782      -0.876       1.164
state[T.NV]           0.0573      0.528      0.109      0.914      -0.978       1.092
state[T.NY]           0.0533      0.512      0.104      0.917      -0.949       1.056
state[T.OH]           0.0792      0.509      0.156      0.876      -0.919       1.077
state[T.OK]          -0.1310      0.516     -0.254      0.799      -1.142       0.880
state[T.OR]          -0.2168      0.512     -0.423      0.672      -1.220       0.787
state[T.PA]          -0.0041      0.510     -0.008      0.994      -1.003       0.995
state[T.RI]           0.2358      0.555      0.425      0.671      -0.851       1.323
state[T.SC]           0.0407      0.514      0.079      0.937      -0.966       1.047
state[T.SD]           0.1516      0.531      0.286      0.775      -0.889       1.192
state[T.TN]           0.1300      0.510      0.255      0.799      -0.870       1.130
state[T.TX]           0.0658      0.508      0.130      0.897      -0.930       1.061
state[T.UT]          -0.3285      0.515     -0.638      0.523      -1.337       0.680
state[T.VA]          -0.0849      0.510     -0.167      0.868      -1.084       0.914
state[T.VT]          -0.5611      0.586     -0.957      0.338      -1.710       0.588
state[T.WA]          -0.1966      0.511     -0.385      0.701      -1.198       0.805
state[T.WI]           0.0701      0.511      0.137      0.891      -0.931       1.071
state[T.WV]           0.0248      0.516      0.048      0.962      -0.987       1.037
state[T.WY]          -0.2014      0.519     -0.388      0.698      -1.219       0.816
masseconlib_est      -0.3064      0.071     -4.303      0.000      -0.446      -0.167
masssociallib_est    -0.1713      0.021     -8.141      0.000      -0.213      -0.130
rlean_rolling2        0.0184      0.002      7.438      0.000       0.014       0.023
1.0/2.0              -3.4546      0.508     -6.795      0.000      -4.451      -2.458
2.0/3.0               0.5424      0.014     37.548      0.000       0.514       0.571
3.0/4.0              -0.2923      0.013    -22.000      0.000      -0.318      -0.266
4.0/5.0               0.3049      0.008     39.388      0.000       0.290       0.320
5.0/6.0              -0.2394      0.011    -21.286      0.000      -0.261      -0.217
6.0/7.0               0.6731      0.012     57.987      0.000       0.650       0.696
=====================================================================================
"""

In [ ]:
YEAR = 2000
masslib = anes[['year','state','masseconlib_est','masssociallib_est']].drop_duplicates()
masslib = masslib.set_index(['state','year'], drop = False)
"""
(ideo_model.predict(pd.DataFrame({
    'state': ['CA','CT','VT'], 

    'masseconlib_est': [masslib.loc[('CA',YEAR),'masseconlib_est'],
        masslib.loc[('CT',YEAR),'masseconlib_est'],
        masslib.loc[('VT',YEAR),'masseconlib_est']],
    'masssociallib_est': [masslib.loc[('CA',YEAR),'masssociallib_est'], 
        masslib.loc[('CT',YEAR),'masssociallib_est'],
        masslib.loc[('VT',YEAR),'masssociallib_est']],

    'year_center': [-20,-20,-20],
    'bea_region': ['Southeast', 'Far West', 'Mideast'], 
    'decade': ['2000','2020','1980'], 
    'rlean_rolling2': [15.5,10.5,-5.5]}))
    .cumsum(axis = 'columns')
)
"""


(ideo_model.predict(pd.DataFrame({
    'state': ['CA','CT','VT'], 
    'rlean_rolling2': [-10.5,-6.7,-8.9],
    'masseconlib_est': [1,0.5,0.8],
    'masssociallib_est': [1,0.5,0.8]}))
    .cumsum(axis = 'columns')
)

#TODO: Create table containing covariates of each state for every election year from 1972-2024 to predict
# distribution of self-placement in each state. Plot average public opinion in each state to visually assess
# estimates

          0         1         2         3         4         5    6
0  0.059320  0.260484  0.426305  0.742604  0.863730  0.978267  1.0
1  0.044110  0.204931  0.352232  0.678579  0.822638  0.970535  1.0
2  0.087291  0.348199  0.529852  0.813974  0.905776  0.985563  1.0

In [ ]:
resent_data = anes[['voter_blacks', 'state', 
    'rlean_rolling2', 'masssociallib_est', 'masseconlib_est']].dropna().copy()
resent_model = OrderedModel.from_formula('voter_blacks ~ state + masseconlib_est + masssociallib_est + rlean_rolling2', 
    distr = 'logit', data = resent_data, hasconst=False).fit(method = 'cg', disp = True)
resent_model.summary() #switching to method 'cg' (conjugate gradient) from default Nelder Mead resolves convergence warnings

Optimization terminated successfully.
         Current function value: 1.873410
         Iterations: 287
         Function evaluations: 603
         Gradient evaluations: 603

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OrderedModel Results
==============================================================================
Dep. Variable:           voter_blacks   Log-Likelihood:                -86967.
Model:                   OrderedModel   AIC:                         1.741e+05
Method:            Maximum Likelihood   BIC:                         1.746e+05
Date:                Sat, 08 Aug 2026
Time:                        00:00:41
No. Observations:               46422
Df Residuals:                   46364
Df Model:                          52
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
state[T.AL]           0.0291      0.526      0.055      0.956      -1.001       1.060
state[T.AR]           0.2652      0.526      0.504      0.614      -0.766       1.297
state[T.AZ]           0.2217      0.526      0.422      0.673      -0.809       1.252
state[T.CA]          -0.0761      0.524     -0.145      0.885      -1.103       0.951
state[T.CO]          -0.0013      0.525     -0.003      0.998      -1.031       1.028
state[T.CT]          -0.2072      0.528     -0.393      0.695      -1.241       0.827
state[T.DE]          -0.1733      0.562     -0.309      0.758      -1.274       0.927
state[T.FL]           0.1095      0.524      0.209      0.834      -0.917       1.136
state[T.GA]          -0.0760      0.524     -0.145      0.885      -1.104       0.951
state[T.HI]           0.4151      0.589      0.704      0.481      -0.740       1.570
state[T.IA]           0.0610      0.526      0.116      0.908      -0.971       1.093
state[T.ID]          -0.1909      0.543     -0.351      0.725      -1.255       0.874
state[T.IL]          -0.1099      0.525     -0.209      0.834      -1.138       0.918
state[T.IN]           0.1293      0.524      0.247      0.805      -0.898       1.156
state[T.KS]           0.0838      0.527      0.159      0.874      -0.950       1.117
state[T.KY]           0.0464      0.529      0.088      0.930      -0.990       1.083
state[T.LA]           0.0417      0.528      0.079      0.937      -0.993       1.076
state[T.MA]          -0.1783      0.527     -0.338      0.735      -1.212       0.855
state[T.MD]          -0.0252      0.527     -0.048      0.962      -1.058       1.008
state[T.ME]          -0.2981      0.538     -0.554      0.579      -1.352       0.756
state[T.MI]          -0.0386      0.524     -0.074      0.941      -1.066       0.989
state[T.MN]           0.0881      0.525      0.168      0.867      -0.941       1.117
state[T.MO]           0.1286      0.525      0.245      0.807      -0.900       1.157
state[T.MS]          -0.0590      0.532     -0.111      0.912      -1.101       0.984
state[T.MT]           0.2084      0.567      0.368      0.713      -0.902       1.319
state[T.NC]          -0.1127      0.524     -0.215      0.830      -1.140       0.915
state[T.ND]           0.4699      0.554      0.848      0.396      -0.616       1.556
state[T.NE]           0.3441      0.531      0.648      0.517      -0.696       1.384
state[T.NH]          -0.1112      0.531     -0.209      0.834      -1.153       0.930
state[T.NJ]           0.0765      0.526      0.145      0.884      -0.955       1.108
state[T.NM]           0.0610      0.534      0.114      0.909      -0.985       1.107
state[T.NV]           0.2847      0.541      0.526      0.599      -0.775       1.345
state[T.NY]          -0.2035      0.526     -0.387      0.699      -1.234       0.827
state[T.OH]           0.0830      0.524      0.159      0.874      -0.944       1.110
state[T.OK]           0.0287      0.529      0.054      0.957      -1.008       1.065
state[T.OR]          -0.3131      0.526     -0.595      0.552      -1.344       0.718
state[T.PA]          -0.0643      0.524     -0.123      0.902      -1.092       0.964
state[T.RI]          -0.1643      0.572     -0.287      0.774      -1.285       0.957
state[T.SC]          -0.1644      0.528     -0.311      0.755      -1.199       0.870
state[T.SD]           0.1142      0.541      0.211      0.833      -0.947       1.175
state[T.TN]           0.3168      0.524      0.604      0.546      -0.711       1.344
state[T.TX]          -0.0065      0.523     -0.012      0.990      -1.031       1.018
state[T.UT]          -0.2165      0.528     -0.410      0.682      -1.251       0.818
state[T.VA]          -0.0795      0.524     -0.152      0.879      -1.107       0.948
state[T.VT]          -0.6631      0.601     -1.104      0.270      -1.840       0.514
state[T.WA]          -0.1709      0.526     -0.325      0.745      -1.201       0.859
state[T.WI]           0.1669      0.525      0.318      0.751      -0.862       1.196
state[T.WV]           0.0614      0.530      0.116      0.908      -0.977       1.099
state[T.WY]          -0.0218      0.530     -0.041      0.967      -1.061       1.017
masseconlib_est       0.2300      0.065      3.557      0.000       0.103       0.357
masssociallib_est    -0.0861      0.019     -4.486      0.000      -0.124      -0.048
rlean_rolling2        0.0146      0.002      6.386      0.000       0.010       0.019
1.0/2.0              -2.2035      0.523     -4.216      0.000      -3.228      -1.179
2.0/3.0              -0.4847      0.017    -29.298      0.000      -0.517      -0.452
3.0/4.0              -0.4552      0.013    -34.443      0.000      -0.481      -0.429
4.0/5.0               0.0601      0.008      7.131      0.000       0.044       0.077
5.0/6.0              -0.5007      0.012    -42.975      0.000      -0.524      -0.478
6.0/7.0              -0.3068      0.012    -25.338      0.000      -0.331      -0.283
=====================================================================================
"""

In [ ]:
(resent_model.predict(pd.DataFrame({
    'state': ['AK','MS','NJ'],  
    'rlean_rolling2': [15.5,16.2,-5],
    'masseconlib_est': [0.5,0.3,1.2],
    'masssociallib_est': [0.5,0.3,1.2]}))
    .cumsum(axis = 'columns')
)

#TODO: Create table containing covariates of each state for every election year from 1972-2024 to predict
# distribution of self-placement in each state. Plot average public opinion in each state to visually assess
# estimates

          0         1         2         3         4         5    6
0  0.075711  0.131678  0.222380  0.452664  0.602566  0.759864  1.0
1  0.081317  0.140797  0.236071  0.471929  0.620972  0.773721  1.0
2  0.084751  0.146342  0.244302  0.483182  0.631528  0.781520  1.0

Create Vote Model to Predict Individual Respondents' Vote as a Function of Self-Placements on the 
Ideology and Aid to Blacks Scales

46570

In [ ]:
"""Load the greater US shapefile data in the working directory under greater_us_shapefiles/ and 
create three plots:
1)
2)
3) """ ""


states = gpd.read_file("path/to/us_states.shp")
states = states.rename(columns={"STUSPS": "state"})

# Keep only the variables needed for plotting
states = states[["state", "geometry"]]

# Merge geometry with ideology estimates
plot_data = states.merge(ideology,
    on="state",
    how="left"
)
decades = np.arange(
    ideology["year"].min() // 10 * 10,
    ideology["year"].max() + 1,
    10
)

plot_data = plot_data[
    plot_data["year"].isin(decades)
]
ncols = 3
nrows = int(np.ceil(len(decades) / ncols))

fig, axes = plt.subplots(
    nrows=nrows,
    ncols=ncols,
    figsize=(15, 4.5 * nrows)
)

# Make axes iterable even if there is only one panel
axes = np.atleast_1d(axes).flatten()

Fit a Second Ordinal Response to Predict Resentment Distribution (Aid to Blacks Scale) as a Function 
of State and Time